# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import medicine_pb2 as medicine__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in medicine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LedgerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterBatch = channel.unary_unary(
                '/med.Ledger/RegisterBatch',
                request_serializer=medicine__pb2.Batch.SerializeToString,
                response_deserializer=medicine__pb2.Ack.FromString,
                _registered_method=True)
        self.TransferBatch = channel.unary_unary(
                '/med.Ledger/TransferBatch',
                request_serializer=medicine__pb2.Transfer.SerializeToString,
                response_deserializer=medicine__pb2.Ack.FromString,
                _registered_method=True)
        self.VerifyBatch = channel.unary_unary(
                '/med.Ledger/VerifyBatch',
                request_serializer=medicine__pb2.VerifyRequest.SerializeToString,
                response_deserializer=medicine__pb2.VerifyResponse.FromString,
                _registered_method=True)


class LedgerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LedgerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterBatch,
                    request_deserializer=medicine__pb2.Batch.FromString,
                    response_serializer=medicine__pb2.Ack.SerializeToString,
            ),
            'TransferBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferBatch,
                    request_deserializer=medicine__pb2.Transfer.FromString,
                    response_serializer=medicine__pb2.Ack.SerializeToString,
            ),
            'VerifyBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyBatch,
                    request_deserializer=medicine__pb2.VerifyRequest.FromString,
                    response_serializer=medicine__pb2.VerifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'med.Ledger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('med.Ledger', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Ledger(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/med.Ledger/RegisterBatch',
            medicine__pb2.Batch.SerializeToString,
            medicine__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/med.Ledger/TransferBatch',
            medicine__pb2.Transfer.SerializeToString,
            medicine__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/med.Ledger/VerifyBatch',
            medicine__pb2.VerifyRequest.SerializeToString,
            medicine__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
