# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: election.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'election.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65lection.proto\x12\x08\x65lection\"\"\n\x0f\x45lectionRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"*\n\rElectionReply\x12\x19\n\x11higher_node_alive\x18\x01 \x01(\x08\"#\n\x0e\x43oordinatorMsg\x12\x11\n\tleader_id\x18\x01 \x01(\t\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x8e\x01\n\x08\x45lection\x12\x43\n\rStartElection\x12\x19.election.ElectionRequest\x1a\x17.election.ElectionReply\x12=\n\x12\x44\x65\x63lareCoordinator\x12\x18.election.CoordinatorMsg\x1a\r.election.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'election_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONREQUEST']._serialized_start=28
  _globals['_ELECTIONREQUEST']._serialized_end=62
  _globals['_ELECTIONREPLY']._serialized_start=64
  _globals['_ELECTIONREPLY']._serialized_end=106
  _globals['_COORDINATORMSG']._serialized_start=108
  _globals['_COORDINATORMSG']._serialized_end=143
  _globals['_ACK']._serialized_start=145
  _globals['_ACK']._serialized_end=162
  _globals['_ELECTION']._serialized_start=165
  _globals['_ELECTION']._serialized_end=307
# @@protoc_insertion_point(module_scope)
