# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ledger2.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ledger2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rledger2.proto\x12\x04meds\"\x9d\x01\n\x05\x45vent\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63tor_id\x18\x02 \x01(\t\x12\x1d\n\x04type\x18\x03 \x01(\x0e\x32\x0f.meds.EventType\x12\x10\n\x08\x62\x61tch_id\x18\x04 \x01(\t\x12\x14\n\x0cpayload_json\x18\x05 \x01(\t\x12\x11\n\tsignature\x18\x06 \x01(\x0c\x12\x14\n\x0clamport_sent\x18\x07 \x01(\x04\"G\n\x08\x45ventAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x18\n\x10lamport_assigned\x18\x03 \x01(\x04\"K\n\rVerifyRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08\x62\x61tch_id\x18\x02 \x01(\t\x12\x14\n\x0clamport_sent\x18\x03 \x01(\x04\"^\n\x0bVerifyReply\x12\x11\n\tauthentic\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nlast_actor\x18\x03 \x01(\t\x12\x18\n\x10lamport_observed\x18\x04 \x01(\x04\"\x12\n\x10\x43hainHeadRequest\"1\n\x0e\x43hainHeadReply\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x0f\n\x07lamport\x18\x02 \x01(\x04*y\n\tEventType\x12\x1a\n\x16\x45VENT_TYPE_UNSPECIFIED\x10\x00\x12\x11\n\rBATCH_CREATED\x10\x01\x12\x14\n\x10SHIPMENT_UPDATED\x10\x02\x12\x12\n\x0eREADY_FOR_SALE\x10\x03\x12\x13\n\x0fSOLD_TO_PATIENT\x10\x04\x32\xa9\x01\n\x06Ledger\x12*\n\x0bSubmitEvent\x12\x0b.meds.Event\x1a\x0e.meds.EventAck\x12\x35\n\x0bVerifyBatch\x12\x13.meds.VerifyRequest\x1a\x11.meds.VerifyReply\x12<\n\x0cGetChainHead\x12\x16.meds.ChainHeadRequest\x1a\x14.meds.ChainHeadReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ledger2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTTYPE']._serialized_start=500
  _globals['_EVENTTYPE']._serialized_end=621
  _globals['_EVENT']._serialized_start=24
  _globals['_EVENT']._serialized_end=181
  _globals['_EVENTACK']._serialized_start=183
  _globals['_EVENTACK']._serialized_end=254
  _globals['_VERIFYREQUEST']._serialized_start=256
  _globals['_VERIFYREQUEST']._serialized_end=331
  _globals['_VERIFYREPLY']._serialized_start=333
  _globals['_VERIFYREPLY']._serialized_end=427
  _globals['_CHAINHEADREQUEST']._serialized_start=429
  _globals['_CHAINHEADREQUEST']._serialized_end=447
  _globals['_CHAINHEADREPLY']._serialized_start=449
  _globals['_CHAINHEADREPLY']._serialized_end=498
  _globals['_LEDGER']._serialized_start=624
  _globals['_LEDGER']._serialized_end=793
# @@protoc_insertion_point(module_scope)
