# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ledger_pb2 as ledger__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ledger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LedgerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitEvent = channel.unary_unary(
                '/meds.Ledger/SubmitEvent',
                request_serializer=ledger__pb2.Event.SerializeToString,
                response_deserializer=ledger__pb2.EventAck.FromString,
                _registered_method=True)
        self.VerifyBatch = channel.unary_unary(
                '/meds.Ledger/VerifyBatch',
                request_serializer=ledger__pb2.VerifyRequest.SerializeToString,
                response_deserializer=ledger__pb2.VerifyReply.FromString,
                _registered_method=True)
        self.GetChainHead = channel.unary_unary(
                '/meds.Ledger/GetChainHead',
                request_serializer=ledger__pb2.ChainHeadRequest.SerializeToString,
                response_deserializer=ledger__pb2.ChainHeadReply.FromString,
                _registered_method=True)


class LedgerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChainHead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LedgerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitEvent,
                    request_deserializer=ledger__pb2.Event.FromString,
                    response_serializer=ledger__pb2.EventAck.SerializeToString,
            ),
            'VerifyBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyBatch,
                    request_deserializer=ledger__pb2.VerifyRequest.FromString,
                    response_serializer=ledger__pb2.VerifyReply.SerializeToString,
            ),
            'GetChainHead': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChainHead,
                    request_deserializer=ledger__pb2.ChainHeadRequest.FromString,
                    response_serializer=ledger__pb2.ChainHeadReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meds.Ledger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meds.Ledger', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Ledger(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meds.Ledger/SubmitEvent',
            ledger__pb2.Event.SerializeToString,
            ledger__pb2.EventAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meds.Ledger/VerifyBatch',
            ledger__pb2.VerifyRequest.SerializeToString,
            ledger__pb2.VerifyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChainHead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meds.Ledger/GetChainHead',
            ledger__pb2.ChainHeadRequest.SerializeToString,
            ledger__pb2.ChainHeadReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
