# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: medicine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'medicine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emedicine.proto\x12\x03med\"i\n\x05\x42\x61tch\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\x12\x11\n\tdrug_name\x18\x02 \x01(\t\x12\x17\n\x0fmanufacturer_id\x18\x03 \x01(\t\x12\x13\n\x0b\x65xpiry_date\x18\x04 \x01(\t\x12\r\n\x05owner\x18\x05 \x01(\t\"I\n\x08Transfer\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\x12\x0c\n\x04\x66rom\x18\x02 \x01(\t\x12\n\n\x02to\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"\"\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\rVerifyRequest\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\"=\n\x0eTransferRecord\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"\xad\x01\n\x0eVerifyResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x15\n\rcurrent_owner\x18\x03 \x01(\t\x12$\n\x07history\x18\x04 \x03(\x0b\x32\x13.med.TransferRecord\x12\x11\n\tdrug_name\x18\x05 \x01(\t\x12\x17\n\x0fmanufacturer_id\x18\x06 \x01(\t\x12\x13\n\x0b\x65xpiry_date\x18\x07 \x01(\t2\x91\x01\n\x06Ledger\x12%\n\rRegisterBatch\x12\n.med.Batch\x1a\x08.med.Ack\x12(\n\rTransferBatch\x12\r.med.Transfer\x1a\x08.med.Ack\x12\x36\n\x0bVerifyBatch\x12\x12.med.VerifyRequest\x1a\x13.med.VerifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'medicine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATCH']._serialized_start=23
  _globals['_BATCH']._serialized_end=128
  _globals['_TRANSFER']._serialized_start=130
  _globals['_TRANSFER']._serialized_end=203
  _globals['_ACK']._serialized_start=205
  _globals['_ACK']._serialized_end=239
  _globals['_VERIFYREQUEST']._serialized_start=241
  _globals['_VERIFYREQUEST']._serialized_end=274
  _globals['_TRANSFERRECORD']._serialized_start=276
  _globals['_TRANSFERRECORD']._serialized_end=337
  _globals['_VERIFYRESPONSE']._serialized_start=340
  _globals['_VERIFYRESPONSE']._serialized_end=513
  _globals['_LEDGER']._serialized_start=516
  _globals['_LEDGER']._serialized_end=661
# @@protoc_insertion_point(module_scope)
